[connections.my_database]
    type="sql"
    dialect="mysql"
    username="kep"
    password="kep"
    host="180.228.37.206" # IP or URL
    port=3306 # Port number
    database="kep_local" # Database name